import 'package:hive/hive.dart';

part 'warehouse_model.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 7)
class WarehouseModel {
  @HiveField(0)
  final WarehouseLocation warehouseLocation;

  @HiveField(1)
  final String id;

  @HiveField(2)
  final String warehouseId;

  @HiveField(3)
  final String warehouseName;

  @HiveField(4)
  final String warehouseDescription;

  @HiveField(5)
  final String warehouseImage;

  @HiveField(6)
  final String warehouseNumber;

  @HiveField(7)
  final List<String> picodes;

  @HiveField(8)
  final String managerName;

  @HiveField(9)
  final String managerNumber;

  @HiveField(10)
  final String managerEmail;

  @HiveField(11)
  final String warehouseEmail;

  @HiveField(12)
  final String warehousePassword;

  @HiveField(13)
  final List<String> deliveryBoys;

  @HiveField(14)
  final String warehouseAddress;

  @HiveField(15)
  final String createdTime;

  @HiveField(16)
  final int version;

  WarehouseModel({
    required this.warehouseLocation,
    required this.id,
    required this.warehouseId,
    required this.warehouseName,
    required this.warehouseDescription,
    required this.warehouseImage,
    required this.warehouseNumber,
    required this.picodes,
    required this.managerName,
    required this.managerNumber,
    required this.managerEmail,
    required this.warehouseEmail,
    required this.warehousePassword,
    required this.deliveryBoys,
    required this.warehouseAddress,
    required this.createdTime,
    required this.version,
  });

  factory WarehouseModel.fromJson(Map<String, dynamic> json) {
    return WarehouseModel(
      warehouseLocation: json['warehouse_location'] != null
          ? WarehouseLocation.fromJson(json['warehouse_location'])
          : WarehouseLocation.empty(), // Default empty if null
      id: json['_id'] ?? '',
      warehouseId: json['warehouse_id'] ?? '',
      warehouseName: json['warehouse_name'] ?? '',
      warehouseDescription: json['warehouse_des'] ?? '',
      warehouseImage: json['warehouse_image'] ?? '',
      warehouseNumber: json['warehouse_number'] ?? '',
      picodes: List<String>.from(json['picode'] ?? []),
      managerName: json['manager_name'] ?? '',
      managerNumber: json['manager_number'] ?? '',
      managerEmail: json['manager_email'] ?? '',
      warehouseEmail: json['warehouse_email'] ?? '',
      warehousePassword: json['warehouse_password'] ?? '',
      deliveryBoys: List<String>.from(json['deliveryboys'] ?? []),
      warehouseAddress: json['warehouse_address'] ?? '',
      createdTime: json['created_time'] ?? '',
      version: json['__v'] ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'warehouse_location': warehouseLocation.toJson(),
      '_id': id,
      'warehouse_id': warehouseId,
      'warehouse_name': warehouseName,
      'warehouse_des': warehouseDescription,
      'warehouse_image': warehouseImage,
      'warehouse_number': warehouseNumber,
      'picode': picodes,
      'manager_name': managerName,
      'manager_number': managerNumber,
      'manager_email': managerEmail,
      'warehouse_email': warehouseEmail,
      'warehouse_password': warehousePassword,
      'deliveryboys': deliveryBoys,
      'warehouse_address': warehouseAddress,
      'created_time': createdTime,
      '__v': version,
    };
  }

  static WarehouseModel empty() {
    return WarehouseModel(
      warehouseLocation: WarehouseLocation.empty(),
      id: '',
      warehouseId: '',
      warehouseName: '',
      warehouseDescription: '',
      warehouseImage: '',
      warehouseNumber: '',
      picodes: [],
      managerName: '',
      managerNumber: '',
      managerEmail: '',
      warehouseEmail: '',
      warehousePassword: '',
      deliveryBoys: [],
      warehouseAddress: '',
      createdTime: '',
      version: 0,
    );
  }
}

@HiveType(typeId: 8)
class WarehouseLocation {
  @HiveField(0)
  final double lat;

  @HiveField(1)
  final double lng;

  WarehouseLocation({
    required this.lat,
    required this.lng,
  });

  factory WarehouseLocation.fromJson(Map<String, dynamic> json) {
    return WarehouseLocation(
      lat: json['lat'] ?? 0.0,
      lng: json['lng'] ?? 0.0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'lat': lat,
      'lng': lng,
    };
  }

  static WarehouseLocation empty() {
    return WarehouseLocation(lat: 0.0, lng: 0.0);
  }
}
