// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwFdaFs181x-W1S25zmVAPADHeJ_Z440',
    appId: '1:760883509884:web:a9cd4ea6afba170ac4a7f9',
    messagingSenderId: '760883509884',
    projectId: 'kwikgroceries-8a11e',
    authDomain: 'kwikgroceries-8a11e.firebaseapp.com',
    storageBucket: 'kwikgroceries-8a11e.firebasestorage.app',
    measurementId: 'G-QMD6Q2ZDXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2uFclqIT0ie1gWtqperj9Chzv5JiGH1Q',
    appId: '1:760883509884:android:bc9a078d4b64643cc4a7f9',
    messagingSenderId: '760883509884',
    projectId: 'kwikgroceries-8a11e',
    storageBucket: 'kwikgroceries-8a11e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkGgYbhB1iHhWA2lTPHBYSycLm8yV1aI4',
    appId: '1:760883509884:ios:b1d63b641cf421e2c4a7f9',
    messagingSenderId: '760883509884',
    projectId: 'kwikgroceries-8a11e',
    storageBucket: 'kwikgroceries-8a11e.firebasestorage.app',
    androidClientId:
        '760883509884-4to8e72dp414gp6ajdc75s0r8et10mh9.apps.googleusercontent.com',
    iosClientId:
        '760883509884-qvn353fqq34pfq5mhk8mq2cj7r958o4d.apps.googleusercontent.com',
    iosBundleId: 'com.digi9.kwik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkGgYbhB1iHhWA2lTPHBYSycLm8yV1aI4',
    appId: '1:760883509884:ios:b1d63b641cf421e2c4a7f9',
    messagingSenderId: '760883509884',
    projectId: 'kwikgroceries-8a11e',
    storageBucket: 'kwikgroceries-8a11e.firebasestorage.app',
    androidClientId:
        '760883509884-4to8e72dp414gp6ajdc75s0r8et10mh9.apps.googleusercontent.com',
    iosClientId:
        '760883509884-qvn353fqq34pfq5mhk8mq2cj7r958o4d.apps.googleusercontent.com',
    iosBundleId: 'com.digi9.kwik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjwFdaFs181x-W1S25zmVAPADHeJ_Z440',
    appId: '1:760883509884:web:a9cd4ea6afba170ac4a7f9',
    messagingSenderId: '760883509884',
    projectId: 'kwikgroceries-8a11e',
    authDomain: 'kwikgroceries-8a11e.firebaseapp.com',
    storageBucket: 'kwikgroceries-8a11e.firebasestorage.app',
    measurementId: 'G-QMD6Q2ZDXF',
  );
}
